spring.application.name=BarberShop
server.port=5050
app.base-url=http://localhost:5050
#MYSQL CONNECTION
spring.datasource.url=jdbc:mysql://localhost:3306/barber-shop-db
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
#THE MAXIMUM SIGN OF IMAGE THAT CAN BE UPLOADED
secreteJwtString=phegondev123456789phegondev123456789

jwt.refresh.expiration=1000L * 60 * 60 * 24 * 7
jwt.access.secret=10577422b6430f2658e5216604e7542e0ca6d15ecd94b8314f48fc2e30e00f7a
jwt.refresh.secret=69cd9cf34baf07f8740c79f052c58ec14abe16748f0f52ea2751b1487aa32763

