CREATE TABLE roles (
    id BIGINT NOT NULL AUTO_INCREMENT,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255) NULL,
    is_active BIT(1) NOT NULL DEFAULT b'1',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_roles PRIMARY KEY (id),
    CONSTRAINT uk_roles_code UNIQUE (code)
);

CREATE TABLE users (
    id BIGINT NOT NULL AUTO_INCREMENT,
    role_id BIGINT NOT NULL,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    phone VARCHAR(30) NULL,
    status VARCHAR(30) NOT NULL,
    last_login_at DATETIME(6) NULL,
    is_deleted BIT(1) NOT NULL DEFAULT b'0',
    deleted_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(id),
    INDEX idx_users_role_id (role_id),
    INDEX idx_users_status (status),
    INDEX idx_users_deleted (is_deleted)
);

CREATE TABLE employees (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NULL,
    employee_code VARCHAR(50) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    gender VARCHAR(20) NULL,
    phone VARCHAR(30) NOT NULL,
    hire_date DATE NOT NULL,
    employment_status VARCHAR(30) NOT NULL,
    commission_type VARCHAR(30) NULL,
    commission_value DECIMAL(10,2) NULL,
    notes VARCHAR(500) NULL,
    is_deleted BIT(1) NOT NULL DEFAULT b'0',
    deleted_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_employees PRIMARY KEY (id),
    CONSTRAINT uk_employees_user_id UNIQUE (user_id),
    CONSTRAINT uk_employees_code UNIQUE (employee_code),
    CONSTRAINT uk_employees_phone UNIQUE (phone),
    CONSTRAINT fk_employees_user FOREIGN KEY (user_id) REFERENCES users(id),
    INDEX idx_employees_status (employment_status),
    INDEX idx_employees_deleted (is_deleted),
    INDEX idx_employees_name (last_name, first_name)
);

CREATE TABLE customers (
    id BIGINT NOT NULL AUTO_INCREMENT,
    customer_code VARCHAR(50) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NULL,
    phone VARCHAR(30) NOT NULL,
    email VARCHAR(150) NULL,
    date_of_birth DATE NULL,
    gender VARCHAR(20) NULL,
    notes TEXT NULL,
    marketing_opt_in BIT(1) NOT NULL DEFAULT b'0',
    last_visit_at DATETIME(6) NULL,
    is_deleted BIT(1) NOT NULL DEFAULT b'0',
    deleted_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_customers PRIMARY KEY (id),
    CONSTRAINT uk_customers_code UNIQUE (customer_code),
    CONSTRAINT uk_customers_phone UNIQUE (phone),
    INDEX idx_customers_name (last_name, first_name),
    INDEX idx_customers_deleted (is_deleted),
    INDEX idx_customers_last_visit (last_visit_at),
    INDEX idx_customers_email (email)
);

CREATE TABLE services (
    id BIGINT NOT NULL AUTO_INCREMENT,
    service_code VARCHAR(50) NOT NULL,
    name VARCHAR(150) NOT NULL,
    category VARCHAR(100) NULL,
    description VARCHAR(500) NULL,
    base_price DECIMAL(10,2) NOT NULL,
    duration_minutes INT NOT NULL,
    is_active BIT(1) NOT NULL DEFAULT b'1',
    is_deleted BIT(1) NOT NULL DEFAULT b'0',
    deleted_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_services PRIMARY KEY (id),
    CONSTRAINT uk_services_code UNIQUE (service_code),
    CONSTRAINT uk_services_name UNIQUE (name),
    CONSTRAINT chk_services_base_price CHECK (base_price >= 0),
    CONSTRAINT chk_services_duration CHECK (duration_minutes > 0),
    INDEX idx_services_active (is_active),
    INDEX idx_services_deleted (is_deleted),
    INDEX idx_services_category (category)
);

CREATE TABLE employee_services (
    id BIGINT NOT NULL AUTO_INCREMENT,
    employee_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    custom_price DECIMAL(10,2) NULL,
    custom_duration_minutes INT NULL,
    skill_level VARCHAR(30) NULL,
    is_active BIT(1) NOT NULL DEFAULT b'1',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_employee_services PRIMARY KEY (id),
    CONSTRAINT uk_employee_service UNIQUE (employee_id, service_id),
    CONSTRAINT fk_employee_services_employee FOREIGN KEY (employee_id) REFERENCES employees(id),
    CONSTRAINT fk_employee_services_service FOREIGN KEY (service_id) REFERENCES services(id),
    CONSTRAINT chk_employee_services_custom_price CHECK (custom_price IS NULL OR custom_price >= 0),
    CONSTRAINT chk_employee_services_custom_duration CHECK (custom_duration_minutes IS NULL OR custom_duration_minutes > 0),
    INDEX idx_employee_services_employee (employee_id),
    INDEX idx_employee_services_service (service_id),
    INDEX idx_employee_services_active (is_active)
);

CREATE TABLE work_schedules (
    id BIGINT NOT NULL AUTO_INCREMENT,
    employee_id BIGINT NOT NULL,
    schedule_date DATE NOT NULL,
    start_time TIME(6) NOT NULL,
    end_time TIME(6) NOT NULL,
    break_start_time TIME(6) NULL,
    break_end_time TIME(6) NULL,
    schedule_type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    notes VARCHAR(500) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_work_schedules PRIMARY KEY (id),
    CONSTRAINT fk_work_schedules_employee FOREIGN KEY (employee_id) REFERENCES employees(id),
    CONSTRAINT chk_work_schedules_time CHECK (end_time > start_time),
    INDEX idx_work_schedules_employee_date (employee_id, schedule_date),
    INDEX idx_work_schedules_date (schedule_date),
    INDEX idx_work_schedules_type (schedule_type),
    INDEX idx_work_schedules_status (status)
);

CREATE TABLE appointments (
    id BIGINT NOT NULL AUTO_INCREMENT,
    appointment_number VARCHAR(50) NOT NULL,
    customer_id BIGINT NOT NULL,
    booked_by_user_id BIGINT NOT NULL,
    assigned_employee_id BIGINT NULL,
    appointment_date DATE NOT NULL,
    start_time TIME(6) NOT NULL,
    end_time TIME(6) NOT NULL,
    status VARCHAR(30) NOT NULL,
    total_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    discount_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    final_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    notes VARCHAR(1000) NULL,
    cancellation_reason VARCHAR(500) NULL,
    cancelled_at DATETIME(6) NULL,
    checked_in_at DATETIME(6) NULL,
    completed_at DATETIME(6) NULL,
    is_deleted BIT(1) NOT NULL DEFAULT b'0',
    deleted_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_appointments PRIMARY KEY (id),
    CONSTRAINT uk_appointments_number UNIQUE (appointment_number),
    CONSTRAINT fk_appointments_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_appointments_booked_by FOREIGN KEY (booked_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_appointments_employee FOREIGN KEY (assigned_employee_id) REFERENCES employees(id),
    CONSTRAINT chk_appointments_time CHECK (end_time > start_time),
    CONSTRAINT chk_appointments_amounts CHECK (
        total_amount >= 0 AND discount_amount >= 0 AND final_amount >= 0
    ),
    INDEX idx_appointments_customer (customer_id),
    INDEX idx_appointments_employee_date (assigned_employee_id, appointment_date),
    INDEX idx_appointments_date_time (appointment_date, start_time),
    INDEX idx_appointments_status (status),
    INDEX idx_appointments_booked_by (booked_by_user_id),
    INDEX idx_appointments_deleted (is_deleted)
);

CREATE TABLE appointment_services (
    id BIGINT NOT NULL AUTO_INCREMENT,
    appointment_id BIGINT NOT NULL,
    service_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    service_name_snapshot VARCHAR(150) NOT NULL,
    price_snapshot DECIMAL(10,2) NOT NULL,
    duration_minutes_snapshot INT NOT NULL,
    line_total DECIMAL(10,2) NOT NULL,
    sort_order INT NOT NULL DEFAULT 1,
    status VARCHAR(30) NOT NULL,
    started_at DATETIME(6) NULL,
    completed_at DATETIME(6) NULL,
    notes VARCHAR(500) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_appointment_services PRIMARY KEY (id),
    CONSTRAINT fk_appointment_services_appointment FOREIGN KEY (appointment_id) REFERENCES appointments(id),
    CONSTRAINT fk_appointment_services_service FOREIGN KEY (service_id) REFERENCES services(id),
    CONSTRAINT fk_appointment_services_employee FOREIGN KEY (employee_id) REFERENCES employees(id),
    CONSTRAINT chk_appointment_services_price CHECK (price_snapshot >= 0),
    CONSTRAINT chk_appointment_services_duration CHECK (duration_minutes_snapshot > 0),
    CONSTRAINT chk_appointment_services_line_total CHECK (line_total >= 0),
    CONSTRAINT chk_appointment_services_sort CHECK (sort_order > 0),
    INDEX idx_appointment_services_appointment (appointment_id),
    INDEX idx_appointment_services_employee (employee_id),
    INDEX idx_appointment_services_service (service_id),
    INDEX idx_appointment_services_status (status)
);

CREATE TABLE payments (
    id BIGINT NOT NULL AUTO_INCREMENT,
    appointment_id BIGINT NOT NULL,
    received_by_user_id BIGINT NOT NULL,
    payment_method VARCHAR(30) NOT NULL,
    payment_status VARCHAR(30) NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    transaction_reference VARCHAR(100) NULL,
    paid_at DATETIME(6) NOT NULL,
    notes VARCHAR(500) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT pk_payments PRIMARY KEY (id),
    CONSTRAINT fk_payments_appointment FOREIGN KEY (appointment_id) REFERENCES appointments(id),
    CONSTRAINT fk_payments_received_by FOREIGN KEY (received_by_user_id) REFERENCES users(id),
    CONSTRAINT chk_payments_amount CHECK (amount > 0),
    INDEX idx_payments_appointment (appointment_id),
    INDEX idx_payments_method (payment_method),
    INDEX idx_payments_status (payment_status),
    INDEX idx_payments_paid_at (paid_at),
    INDEX idx_payments_reference (transaction_reference)
);
